# Generated by Django 2.2.6 on 2020-07-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
