# Generated by Django 2.2.6 on 2020-07-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20200722_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='url',
        ),
    ]
