# Generated by Django 2.2.6 on 2020-07-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_auto_20200722_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='url',
            new_name='slug',
        ),
    ]
