# Generated by Django 2.2.6 on 2020-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_auto_20200722_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
